### PR TITLE
HintText contains substring if it's too long.

### PR DESCRIPTION
**Pull request by avently**
Now if hintText is too long it is replaced with dots. I think we need to show substring of that text. 
Better to see something than nothing, right?

### CODE REVIEW

**Comment by avently** [comment]
@menny do you want this changes?  I'll remove mHintOverflowLabel from everywhere if you are agree (this will fix tests).

**Comment by menny** [comment]
@avently yes, that's fine: you can remove `mHintOverflowLabel`

**Comment by avently** [comment]
@menny done. What is codecov wanting from me?

**Comment by menny** [comment]
Don't worry about that.

**Comment by menny** [comment]
Thanks

**Pull request merged**
