### PR TITLE
modify gesture drawing type to tail-effect

### PR DESCRIPTION
**Pull request by suntabu**
I've made a tail effect for gesture typing path just like below:
231506b0vzmvvx0tvjm3yo

### CODE REVIEW

**Comment by menny** [comment]
This is cool. I'd like this in.
Could you fix the issues at https://circleci.com/gh/AnySoftKeyboard/AnySoftKeyboard/1158?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by suntabu** [comment]
@menny  Hi, I've fixed some errors, but others errors are not caused by my code. And I'm not so practicing with testing driven developing.  if more testing code needed, please tell me a bit more details on how to do it. I'd like to add them.

**Comment by menny** [comment]
@suntabu I send you a PR (to your own fork) with a fix commit. Then you should merge that into your `master` branch. That will re-trigger a build here. I think.

**Comment by menny** [comment]
@suntabu please merge https://github.com/suntabu/AnySoftKeyboard/pull/1 into your fork.
I think it will fix the issue

**Comment by menny** [comment]
Thanks

**Pull request merged**
