### PR TITLE
Colorize navbar support added.

### PR DESCRIPTION
**Pull request by paledega**
I added view thats height equal navbar height
and I added flag in window

Navbar colorize now supporting.

Example app: https://gitlab.com/frknkrc44/superboard
Example app2: https://gitlab.com/droidtr/org.droidtr.keyboard

### CODE REVIEW

**Comment by paledega** [comment]
I forgot tiny import :D

**Comment by menny** [comment]
thanks!

**Comment by menny** [comment]
I think we can optimize this a bit. I understand that we must have a view behind the nav-bar?
Also, this is only possible with API-level>20?

**Comment by paledega** [comment]
navbar flag avaible on only api20+

**Comment by frknkrc44** [comment]
Code is not tried with SDK < 21 versions, because we don't have any device for test that

**Comment by paledega** [comment]
Screenshot_20190618-001157
droidtr keyboard support this.
(navbar has blank view )

**Comment by frknkrc44** [comment]
Also SuperBoard supports this
Screenshot_2019-06-18-00-17-00

**Comment by paledega** [comment]
@menny Could you add this feature in anysoft?

**Comment by menny** [comment]
@paledega yes, sure. Do you want to implement this?

**Comment by menny** [comment]
I think I got this working. See attached gif

**Comment by menny** [comment]
I'll create  new PR, and push my changes there. So, closing this one

**Comment by menny** [comment]
new PR: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1773

**Pull request closed without merging**
