### PR TITLE
Swipe2fingers

### PR DESCRIPTION
**Pull request by mtudora**
Fixed the 2 fingers swipe, left, right, and you can even choose up or down

### CODE REVIEW

**Comment by menny** [comment]
@mtudora thanks for the PR! This help a lot.

Can you `drop` the two merge commits, and rebase your code with `git pull --rebase upstream master`?

**Comment by mtudora** [comment]
Hello,
Should i do a squash or what do you mean by dropping the merges? Should i call git pull --rebase upstream master from the same branch swipe2fingers right?
Thank you,Monica.
 

    On Monday, July 25, 2016 6:23 PM, Menny Even Danan <notifications@github.com> wrote:
 

 @mtudora thanks for the PR! This help a lot.Can you drop the two merge commits, and rebase your code with git pull --rebase upstream master?—

**Comment by menny** [comment]
no need to squash, just do `git rebase -i upstream master` and `drop` the merge commits.
Then rebase your (single) commit on top of _master_ with `git pull --rebase upstream master`

**Comment by mtudora** [comment]
i did it but i see if failed a test because of the changes i've done, should i fix it to pass the test? 

    On Monday, July 25, 2016 7:14 PM, Menny Even Danan <notifications@github.com> wrote:
 

 no need to squash, just do git rebase -i upstream master and drop the merge commits.
Then rebase your (single) commit on top of master with git pull --rebase upstream master—

**Comment by menny** [comment]
I want this in. So here's what I'm going to do:
I'll create a new branch `gesture-analyser` and you should create a new PR and target it there.
At that point, I'll merge it and fix whatever needed and merge it to _master_
Sounds good?

**Comment by mtudora** [comment]
Ok sounds good.

Sent from my HTC

----- Reply message -----

**Comment by menny** [comment]
@mtudora please push your commit to https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/gesture-analyser

**Comment by menny** [comment]
closing this in favor of the other PR

**Pull request closed without merging**
