### PR TITLE
Be able to choose custom path for backup and restore #1780

### PR DESCRIPTION
**Pull request by lubenard**
This pull request allow you to choose the path to backup / restore your preferences (aka issue #1780)

I attached the screenshot of a android device < 4.4

If android > 4.4, it will use android default intent, allowing more options.

Screenshot_1593962342

Screenshot_1593962332

### CODE REVIEW

**Comment by menny** [comment]
run: `./gradlew googleJavaFormat` to fix the formatting issue.

**Comment by lubenard** [comment]
Yes, i know, but running it does not seem to have en effect, git not showing the file as modified

**Comment by lubenard** [comment]
With java transitionning from 10 to 11, it was a bit complicated, but here it is !

**Comment by menny** [comment]
this is great! thank you!

**Pull request merged**
