### PR TITLE
Bump compile and target SDKs to 29

### PR DESCRIPTION
**Pull request by eyedol**
So far, I'm able to run the app on API 29 and above without any crashes from the screens that I visited. Let me know if there' are specific things I need to check for this dump that I'm not aware of.

Here are sample screenshots of my tests so far.

| Screenshots 1 | Screenshots 2|
| ------ | ----- |
|  |  |
| Screenshots 3 | Screenshots 4 |
|  | |

### CODE REVIEW

**Comment by menny** [comment]
On which devices and Android versions have you tested?

**Comment by eyedol** [comment]
> On which devices and Android versions have you tested?

I tried on 30, 29, 23 emulators. I'll try on a 28 later today to make sure

**Comment by menny** [comment]
this is great!
Thank you. I'll wait for your results with 28, and merge if it's good.

**Review by menny — APPROVED** [review]

**Comment by eyedol** [comment]
@menny no worries. Glad I could contribute back to this project. Thanks for the merge. Here' are screenshots of my test with API 28. I'll be moving on to #2344

| Screenshots 1 | Screenshots 2|
| ------ | ----- |
|  |  |
| Screenshots 3 | Screenshots 4 |
|  | |

**Pull request merged**
