### PR TITLE
Minor verbiage change

### PR DESCRIPTION
**Pull request by toolstack**
Make failures due to storage access more gramatically correct.

### CODE REVIEW

**Comment by menny** [comment]
If this PR checks fail, you'll need to rebase to latest _master_.

**Comment by toolstack** [comment]
Will do.

**Comment by toolstack** [comment]
> If this PR checks fail, you'll need to rebase to latest _master_.

Done.

**Review by menny — APPROVED** [review]

**Comment by toolstack** [comment]
@menny Looks like everything but the source formating passed, is that something I need to fix?

**Comment by menny** [comment]
You can run: /gradlew googleJavaFormat

**Comment by toolstack** [comment]
> You can run: /gradlew googleJavaFormat

@menny done.

**Review by menny — APPROVED** [review]

**Pull request merged**
