### PR TITLE
Add dictionary files

### PR DESCRIPTION
**Pull request by sslaia**
Added some documents for improving the Nias dictionary

### CODE REVIEW

**Comment by menny** [comment]
Have you tested this? And it works as desired?

**Comment by menny** [comment]
Also, can you update addons/languages/nias/apk/src/main/play/release-notes/en-US/alpha.txt to reflect this change?

**Comment by sslaia** [comment]
> Also, can you update addons/languages/nias/apk/src/main/play/release-notes/en-US/alpha.txt to reflect this change?

Sorry I forgot this one. But I can't do it at the moment. I've got COVID and laying in bed. I'll work on this as soon as I revover

**Comment by sslaia** [comment]
Close for later time

**Comment by menny** [comment]
Feel better soon!

**Pull request closed without merging**
