### PR TITLE
Reorder right parenthesis and brackets

### PR DESCRIPTION
**Pull request by steelman**
Make the order of right parenthesis, square and curly brackets match the
order of left ones, the same way '<' and '«' match their counterparts.

### CODE REVIEW

**Comment by menny** [comment]
Nice catch. Thanks.

**Comment by menny** [comment]
You're change will be available in the next release. Also, in the next beta which will be available later today

**Comment by steelman** [comment]
I think there are more patches like this to be made. For example when long-pressing the upper row keys (qwerty...), the digits (0-9) aren't always the highlighted by default. Are you interested in such fixes?

**Comment by menny** [comment]
@steelman of course, anything you think can make the keyboard better.

**Pull request merged**
