### PR TITLE
adding theme api for changing suggestion selection highlight

### PR DESCRIPTION
**Pull request by JohnOberhauser**
### Description
- adding a field to `keyboard_theme_api` to customize the suggestion selection highlight color

selectionBackground

### CODE REVIEW

**Review by menny — APPROVED** [review]
haha, I can't believe I missed that. Thank you!

**Comment by JohnOberhauser** [comment]
not sure why `app-all-sdks-tests` is failing.  I'm unable to rerun it.

**Review by menny — CHANGES_REQUESTED** [review]
This is great: before I merge this, I want you to use this in at least one theme (in addition to the base theme).
I'm thinking, very dark gray for the _light_ themes, and regular gray for the _dark_ themes.

I would also like to see usage for the gesture theming you added in a previous PR.

**Comment by menny** [comment]
will continue this at https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2988

**Pull request closed without merging**
