### PR TITLE
Repaint branch www

### PR DESCRIPTION
**Pull request by VitaliPom**
Fixed bug. Re-applying.

### CODE REVIEW

**Comment by VitaliPom** [comment]
waiting for checks and tests to run, applying ahead of time.

**Comment by VitaliPom** [comment]
jeeeeeeezes now conflicts. Fixing again....CLOSE

**Comment by VitaliPom** [comment]
I removed padding bottom values since they were incomplete and broke the repaint algorithm. Tests fail now, I will fix the 'padding' support and re-commit.

**Comment by menny** [comment]
This is pretty large. It will take me some time to review.

**Comment by menny** [comment]
closing this in favor of https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/1762

**Pull request closed without merging**
