### PR TITLE
Added Hindi

### PR DESCRIPTION
**Pull request by martholomew**
- [ ] Test and fix any problems on the keyboard
- [ ] "zwj" and "znwj" popups are blank

@RahiAkherajot , for a T9 layout, would you type in English letters and it would convert to Hindi letters?

### CODE REVIEW

**Comment by RahiAkherajot** [comment]
> * [ ]  Test and fix any problems on the keyboard
> * [ ]  "zwj" and "znwj" popups are blank
> 
> @RahiAkherajot , for a T9 layout, would you type in English letters and it would convert to Hindi letters?

No, please. I want to keyboard in Hindi alphabets, and converting from English to Hindi is not easy for anyone.
There are 34 consonants and 11 vowels in this language.
10 vowels have different signs when added to a consonant, there are 15 signs including signs of vowels.

Vowels
अ आ इ ई उ ऊ ऋ ए ऐ ओ औ
Consonants
क ख ग घङ 
च छ ज झ ञ
ट ठ ड ढ ण
त थ द ध न
प फ ब भ म
य र ल व श
ष स ह ळ
Signs
् ा ि ी ु ू े ै ो ौ ं ः ॅ ँ ़
Numbers
० १ २ ३ ४ ५ ६ ७ ८ ९
Please give these numbers top position.
Also add these characters at suitable position
ॐ ₹ ऽ 卐 ॰ । ॥ | 
It will make a complete Hindi keyboard

**Comment by RahiAkherajot** [comment]
For a T9 layout you can put
। , ? ! ॥ ॰ १ 1
अ आ इ ई उ ऊ ऋ २ 2
ए ऐ ओ औ ३ 3
क ख ग घ ङ ४ 4
च छ ज झ ञ ५ 5
ट ठ ड ढ ण ६ 6
त थ द ध न ७ 7
प फ ब भ म ८ 8
य र ल व श ष स ह ळ ९ 9
् ं ः ँ ॅ ़ *
space ० 0 enter
ॐ ₹ ! : - _ #

These vowels changes into 
ा ि ी ु ू ृ २ 2
े ै ो ौ ३ 3
when there is a consonant before them

**Comment by martholomew** [comment]
Very useful, the T9 layout will require a *bit* of messing with the code, however; but I do need to mess with that same code for other functionalities, I'll see if I can't get started on it.

**Comment by martholomew** [comment]
Hey, @menny , seems I can't approve my own pull requests. Could we merge this pr and I'll leave the t9 keyboard for later?

**Pull request merged**
