### PR TITLE
Add lean light theme.

### PR DESCRIPTION
**Pull request by danielegobbetti**
Most of the graphics were with imagemagick using convert -negate on the dark graphics.

There is a problem with the smiley Key, since it's defined in an XML file that is not
theme dependent, as far as I can tell. The smiley key is hence currently invisible
but working.

### CODE REVIEW

**Comment by menny** [comment]
Thanks!
It looks good on my device. I'm looking into the smiley icon problem.

Can you help one with another task?

**Comment by danielegobbetti** [comment]
I can try, which task are you referring to?

Thanks for the fast merge  :)

**Comment by menny** [comment]
#506 or #502 are good options

**Comment by danielegobbetti** [comment]
Well, I'll try but I don't know if I'll be able to help, the codebase is pretty big and I just worked on the res files so far.

I'll try to invert the gradient on the keyboard to workaround the smiley issue, shall I do a new pull request of can I just attach a patch here? It should literally be a two-line change.

**Comment by menny** [comment]
Regarding the theme, open a new PR. Also, can you look at removing the
underline brackets from the function keys (shift, space, etc)

**Pull request merged**
