### PR TITLE
Add dash variations and square root symbol to symbol tables

### PR DESCRIPTION
**Pull request by simon-v**
Adding the square root symbol required moving the division symbol to the multiplication symbol key to make room.

### CODE REVIEW

**Comment by menny** [comment]
Hi, @simon-v , what are you plans with this?

**Comment by simon-v** [comment]
Eventually? To extend the symbols keyboards to include every commonly and semi-commonly used symbol, perhaps using PerfectKeyboard as an example.

Right now, though, i *think* i got all of the bugs with this contribution. The build on Shippable seems to fail during the install phase, not the build phase. There isn't much i can do about that.

**Comment by simon-v** [comment]
1. I can't figure out what Shippable is complaining about. All five XML validators i tried seem to think the file is well-formed, and Shippable itself doesn't disclose the exact nature of the complaint.
2. I can't figure out how to build the project locally, despite following the setup and build instructions very carefully.
3. I can't help but feel extremely frustrated about both of those.

**Comment by menny** [comment]
I'm really sorry about that - it seems that Shippable is broken.

Can you squash all those commits into one, and force push to this PR. I'll merge even if shippable is failing.

**Comment by simon-v** [comment]
I think i got it.
I'd prefer if a few simple quality tests were made after merging in case i'm missing something.

**Pull request merged**
