### PR TITLE
Update string.xml of Persian language pack

### PR DESCRIPTION
**Pull request by ghasemiHussein**
There is a person name in Persian layouts. It is ugly on UI.
I just remove it.

### CODE REVIEW

**Comment by menny** [comment]
can you close this PR and re-create it against `release-branch-addons-v4.0-r1.1` branch?

**Comment by menny** [comment]
The easiest way is by using the web UI on github. Go to https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/release-branch-addons-v4.0-r1.1/addons/languages/persian/pack/src/main/res/values/strings.xml and make the change.

**Comment by ghasemiHussein** [comment]
I use the link you provided but i'm not sure if i do it right. i'm new to github. tell me if i should do it diffrently.
thanks

**Comment by ghasemiHussein** [comment]
OK. I did it.

**Pull request closed without merging**
