### PR TITLE
Fix and improve translations in de

### PR DESCRIPTION
**Pull request by dueringa**
I tried to fix and improve some of the German translations, because I had no idea what some of them do using the German locale. I also tried to remove some inconsistencies.

### CODE REVIEW

**Comment by menny** [comment]
Thanks. The supported way to contribute translations is by going to https://crowdin.com/project/anysoftkeyboard and to provide you additions and fixes there

**Comment by menny** [comment]
I pull new translations from there regularly.

**Comment by dueringa** [comment]
Can I simply upload the edited strings.xml file there?

**Comment by dueringa** [comment]
Thanks, got it, I'll close this PR then

**Comment by menny** [comment]
Cool. I'll publish a new beta today or tomorrow, if you wish to verify

**Pull request closed without merging**
