### PR TITLE
Adding change layout button to bottom row 

### PR DESCRIPTION
**Pull request by mhdzli**
Since the bottom row is fixed due to special Persian characters, with adding the change layout button to bottom row it will be possible for users to change the top row.

### CODE REVIEW

**Comment by menny** [comment]
Can you attach a screenshot?

**Comment by menny** [comment]
@mhdzli can you attach a screenshot?

**Comment by mhdzli** [comment]
> @mhdzli can you attach a screenshot?

I don't have access to my system nutil next Wednesday. I'll do that in next week.

**Comment by mhdzli** [comment]
These two pictures are English and Persian layouts with `Regular sized keys`  as top row for Persian and English layout and `Regular` for bottom  row in English layout.

The bottom row is fixed (look at question mark and zero width space in Persian layout bottom row).

I can use the layout name button in top row to switch between these two layouts.

If I change the top row to `navigation keys` and bottom row to  `Alternate with mice` I will have these layouts:




I can switch to Persian layout from English by tap on `switch layout` button in bottom row, but only by swiping to right I can switch to English layout from Persian since there is no button for that.

Add `switch layout` button to Persian layout bottom row makes it easier to change the top row.

**Comment by mhdzli** [comment]
It' has been mentioned in one of play store comments. I can send you a screenshot of the Persian layout with `switch layout` button in bottom row next week.

**Review by menny — APPROVED** [review]

**Pull request merged**
