### PR TITLE
Added new generation bottom row without apostroph

### PR DESCRIPTION
**Pull request by lubenard**
In french azerty keyboard, there is 2 apostroph in the keyboard. And one is on the bottom row layout

### CODE REVIEW

**Comment by menny** [comment]
can you attach a screenshot of the layout?

**Comment by lubenard** [comment]
Yes, here it is !

**Comment by jayant-live** [comment]
hey Bro i am a non tech guy would you please compile and make a custom bottom generic row , 
with just 
1. emoji Key 
2. exclamation ( ! ) key 
3.  space key 
4.  question mark key (?)
5. and enter key 

please make one for me i will be thankfull !!

**Comment by lubenard** [comment]
Yep, can definitely do it as soon as i get my hand on my laptop, i'm currently on vacation

**Pull request merged**
