### PR TITLE
Fix Combining Characters when Shift Key is Toggled and Add AutoCap Var to Keyboard Files

### PR DESCRIPTION
**Pull request by menny**

### CODE REVIEW

**Comment by martholomew** [comment]
@menny I can't merge pull requests on this repository.

**Comment by menny** [comment]
@martholomew I sent you an invite to the maintainers' group. After you accept, you should be able to merge.

**Comment by menny** [comment]
oh, and you'll need to `approve` the PR first.

**Comment by martholomew** [comment]
Awesome, thanks.

**Comment by menny** [comment]
Thank you. You can now approve and merge any PR (other than yours).

If this PR fixes any open issue, please close them (and mark them for milestone 1.10-r4)

**Pull request merged**
