### PR TITLE
Added missing characters for Hindi language

### PR DESCRIPTION
**Pull request by Raj9039852537**
Consider updating Hindi add-on so it can become usable

### CODE REVIEW

**Comment by menny** [comment]
Thank you. Can you add context and reasoning? All I see is that you removed characters and added others

**Comment by Raj9039852537** [comment]
In normal inscription layout also these characters are there but with ask it is impossible to type some words like "नही" "हाँ" "लेना" etc due to these missing characters
Here is the physical keyboard image clearly showing missing symbols from ask
[Hindi keyboard image from will feature for reference](https://upload.wikimedia.org/wikipedia/commons/9/99/Devanagari_INSCRIPT_Keyboard.JPG) 

Also every other keyboard that support Hindi have these characters included.

It is also reported [Here](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/3003)

**Comment by Raj9039852537** [comment]
Also he character I changed (not removed) are already there with shift and long press action which is just normal for those characters as per the given Wikimedia image above

**Comment by menny** [comment]
thank you for the context

**Review by menny — APPROVED** [review]

**Comment by Raj9039852537** [comment]
Thanks 🤝

**Pull request merged**
