### PR TITLE
Migrate to Androix

### LINKED ISSUE #2344: Use androidx
min SDK level 14

### PR DESCRIPTION
**Pull request by eyedol**
- Upgrade Android support library to 28.0
- Enabled Jetifier
- Use AS to migrate from support library use to Androidx. All `androidx` artifacts are 1.0.0
- Bump minSDK to 14 as required by androidx packages
- Bump AGP to v3.6.4 

Fixes #2344

### CODE REVIEW

**Comment by apederson94** [comment]
Has there been any recent progress on this? 

I have a little side project that I wanted to get working that relies on androidx and min sdk 14. I have a branch working locally, but I doubt it would be considered ready to merge.

**Comment by eyedol** [comment]
@apederson94 no progress on it. The changes are significant and will require a bit of planning in executing them. I know ASK has an interest in migrating to Androidx but until the time comes for them to make it happen, these changes won't be easily mergeable -- so I have halted my work on it.

**Comment by menny** [comment]
I've started rolling out v1.10-r4 today.
The next release will be v1.11-r1, and it will have min-sdk 14, and will use android-x libraries. I think now is a good time to re-start work on this PR.

Thank you

**Comment by eyedol** [comment]
> I've started rolling out v1.10-r4 today.
> The next release will be v1.11-r1, and it will have min-sdk 14, and will use android-x libraries. I think now is a good time to re-start work on this PR.
> 
> Thank you

Awesome. I'll get back to it then.

**Comment by menny** [comment]
I think we can close this PR. A different PR has introduced androidx: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2852

**Pull request closed without merging**
