### PR TITLE
Continuing https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2864

### LINKED ISSUE #2815: Backup failes due to missing directory
### Steps to reproduce
1. Start ASK
2. Select three dot menu
3. Select Backup
4. Click Backup

### Expected behaviour
Backup file should be created in /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files.

### Actual behaviour
Error message is displayed: Failed! Failed to backup your data due to Failed to of storage folder /storage/emulated/0/Android/data/com.menny.android.anysoftkeyboard/files

This is because the "com.menny.android.anysoftkeyboard" directory does not yet exist in /storage/emulated/0/Android/data.  If I manually create it, the backup works correctly.

Taking a quick look at the source code it looks like line 133 of AnyApplication.java is the likely culprit:
```
new File(externalFolder, "/Android/data/" + BuildConfig.APPLICATION_ID + "/files/"),
```
As it looks like it assumes all paths already exist above "files".

I'm not a java programmer, but doing a quick search, perhaps something like:
```
new File(externalFolder, "/Android/data/" + BuildConfig.APPLICATION_ID + "/files/").mkdirs(),
```
would solve the issue?

**Android OS version:**
LineageOS 17.1 or 18.1, no GAPPS or microG.

**Device manufacturer and model:**
Muliptle: OnePlus 5,7,8t, Pixel 4, Samsung Galaxy Tab s5e

**List of installed add-ons (like languages, or themes):**
None

### PR DESCRIPTION
**Pull request by menny**
Resolves #2815

### CODE REVIEW

**Comment by menny** [comment]
@toolstack can you take a look at this PR? Looks good?

**Comment by toolstack** [comment]
> @toolstack can you take a look at this PR? Looks good?

@menny Looks good to me.

**Comment by menny** [comment]
@toolstack can you also verify on your device?

**Comment by toolstack** [comment]
> @toolstack can you also verify on your device?

@menny Can do, will verify it later tonight.

**Comment by toolstack** [comment]
> > @toolstack can you also verify on your device?
> 
> @menny Can do, will verify it later tonight.

@menny Some free time just cleared up and I tested it successfully on a fresh install, looks good to go.

Thanks for merging this fix.

**Pull request merged**
