### PR TITLE
Add a modified QWERTY Latin keyboard with symbols and top/bottom rows

### PR DESCRIPTION
**Pull request by mirfatif**
The only QWERTY Latin keyboard with symbols needs some improvements for simplicity lovers.
Appearance was a bit cluttered particularly due to haphazard number of characters in hint labels.
Some keys replaced.
Bottom row customized accordingly.
New layout fits better with my newly added symbol keyboards and customized switch key labels in accompanying commit.
Layout also syncs with my newly added Urdu keyboard in accompanying commit.

### CODE REVIEW

**Comment by Sylvain303** [comment]
hi @mirfatif, do you know how to build a custom layout?
Could you help me to build my own? So we may also answer: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2409

Regards,
Sylvain.

**Comment by mirfatif** [comment]
> hi @mirfatif, do you know how to build a custom layout?

That's what I did in this PR. See the files changed in the only commit I made.

> Could you help me to build my own? So we may also answer: #1529

Simplest approach would be to copy one of the existing layouts, which you think is close to your desired layout. Then make changes to files as per your needs.

**Comment by Sylvain303** [comment]
@mirfatif Thanks, I gonna try.
I never made an android app.
I think to build it I need to install [android studio](https://developer.android.com/studio) or such.

I would like to reorder some sub-key appearing in the keyboard and to enlarge the space bar, and/or remove some key I never use. My actual layout is  FR-Qwerty (in android setup) How do I ensure which one it is?

I suppose this is this one: https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/addons/languages/french/pack/src/main/res/xml/qwerty_with_symbols.xml

But I see no row with the space bar.

Your PR seems to use one row to define a space bar: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/2409/files#diff-676d1cb228b5266f2f51c66dfaa3993b0458021fb0e87604831f7cace91b642aR200

Is the XML file format for the keyboard layout described somewhere? Or a layout editor could generate it?
Can a layout rendering could be made by some tools before, for checking or screenshoting purpose?

May be there's a better place to discuss, I don't know where for now. :wink:

**Comment by mirfatif** [comment]
> May be there's a better place to discuss, I don't know where for now. wink

You can reach me at [xda](https://forum.xda-developers.com/member.php?u=7805402)

**Comment by mirfatif** [comment]
@menny if you are not considering to merge this at the moment, may I build this layout as addon and publish on Play Store?

**Pull request closed without merging**
