### PR TITLE
Added horizontal scrolling layout for view item

### PR DESCRIPTION
**Pull request by lubenard**
Now, for any to long string in menus, the text will be left scrolling. 

This is to be able to read what can be in parenthesis

### CODE REVIEW

**Comment by lubenard** [comment]
This fail is weird. 

This is like it failed to start.

Already passed it 3 times at home, and it successfully passed.

**Comment by menny** [comment]
I've seen that too a few days ago. Could be a github infrastructure issue, which seems to be resolved now.

Can you rebase this PR?

**Comment by menny** [comment]
@lubenard would you like to take a shot at https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/2313 ?

**Comment by lubenard** [comment]
Yes, i'll see what i can do !

**Pull request merged**
