### PR TITLE
addition of new german keyboard

### PR DESCRIPTION
**Pull request by Pippo8291**
* added keyboard with ö,ä,ü keys but without ß

### CODE REVIEW

**Comment by menny** [comment]
Thank you. What is the purpose of this keyboard? Is this a personal preference or a known variant?

**Comment by Pippo8291** [comment]
thanks for your reply. To be honest it may be a kind of personal flavour, but i found no keyboard that shows the german ü, ä and ö key but hiding the ß key, which was the keyboard within my old device and which is the default setup of german keyboards for the computer. 
maybe i should change the name displayed within the spacebar.

**Review by menny — APPROVED** [review]

**Comment by Pippo8291** [comment]
does a re-run fix this or do i have to add sth for the linters check?

**Comment by menny** [comment]
well, look at that..

**Comment by Pippo8291** [comment]
That was really quick. Thanks. Sign up is only possible with google play right?

**Comment by menny** [comment]
yes, play store only

**Pull request merged**
