### PR TITLE
Replacing the Slovak dictionary file with a bigger one

### PR DESCRIPTION
**Pull request by ViktorWalter**
The previous dictionary for Slovak language was very lacking. Besides the small number of core words, it completely omits declinations, negations, etc..., making typing with it a chore. 
I have replaced the dictionary with a significantly larger one - 1.8 million words instead of the previous 31 thousand.
This one also includes the aforementioned modifiers, since as far as I know, ASK does not have a system for generating them dynamically.
I have generated the wordlist file using my scripts from [here](https://github.com/ViktorWalter/ASK_slovak_better).
The wordlist originates from Slovak wikipedia and opensubtitles.org, according to the [source](http://p.brm.sk/sk_wordlist/).

### CODE REVIEW

**Comment by menny** [comment]
seems like a very large dictionary to keep in memory, have you tested that?

**Comment by ViktorWalter** [comment]
Yeah, I'm running it on my phone. I haven't noticed any slowdown whatsoever. I know that it's relatively big, but before submitting it I checked and I'm seeing a significantly bigger language pack included in the repo already - Arabic is >27MB zipped.

**Comment by menny** [comment]
@ViktorWalter I want to include this change in the release happening right now.
Can you resubmit the PR but rebased to `release-branch-addons-v4.1-r2`. I tried to do it here, on my end but it didn't work as expected.

**Comment by menny** [comment]
Also, do you think we can reuse your scripts for other languages?

**Comment by ViktorWalter** [comment]
I can try. Feel free to use the scripts, but at least the parser is pretty specific to the wordlist format of the source - `word #count` per line. You'd have to change the vim command to apply for a given line format.

**Comment by ViktorWalter** [comment]
Ok, I resubmitted it on [3196](https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3196). I had to cherry pick the commit, since there seem to be many differences from the master and I didn't want to risk messing it up.

**Comment by menny** [comment]
Makes sense. Thank you

**Comment by menny** [comment]
Closing this PR. The change was merged with: https://github.com/AnySoftKeyboard/AnySoftKeyboard/pull/3196

**Pull request closed without merging**
