### PR TITLE
FIX *Remove PhoneKeyboard from listed keyboards #1610*

### PR DESCRIPTION
**Pull request by VitaliPom**
Now typing is a little bit more easy :)

DESCRIPTION "Keyboard just turned out symbols to be more intuitive and
now symbols will not include the irrelevant Numpad keyboard. It will pop
up only when keyboard for num pad is set up in a web app mobile view.
So if you need to type up numbers, you will have it. For everything else you have full support for symbols from now on."

### CODE REVIEW

**Comment by VitaliPom** [comment]
@menny

**Comment by VitaliPom** [comment]
https://youtu.be/QUJ71GWWV0Y

**Comment by VitaliPom** [comment]
@menny confirm this one as well please. It's also a quick fix to a common problem...

**Comment by menny** [comment]
I'm closing this. It is way back. If you want to try again, open a new PR

**Pull request closed without merging**
