### PR TITLE
Improved the language pack for Slovenian

### PR DESCRIPTION
**Pull request by zeko9381**
I know there's already a language pack for Slovene, but the layout has additional keys for š, đ, č, ć and ž, which makes the keyboard extremely cramped and impossible to type on. This is also my first ever real contribution to a project, so please be gentle :sweat_smile:

### CODE REVIEW

**Comment by menny** [comment]
@zeko9381 is this the pack you want to improve? https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.slovene

**Comment by zeko9381** [comment]
> @zeko9381 is this the pack you want to improve? https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.slovene

yes

**Comment by menny** [comment]
got it.
In that case, please change the package names to `com.anysoftkeyboard.languagepack.slovene`

**Comment by zeko9381** [comment]
will do

**Comment by zeko9381** [comment]
Here you go

**Comment by zeko9381** [comment]
I don't understand why the check is failing. It runs fine on my machine.

**Comment by menny** [comment]
I think the CI machine crashed: `The message received from the daemon indicates that the daemon has disappeared.`.
I'll re-run the checks

**Review by menny — APPROVED** [review]

**Comment by menny** [comment]
Thank you!

**Pull request merged**
