### PR TITLE
Work in progress - Implement experimental gesture typing

### PR DESCRIPTION
**Pull request by jtjj222**
From issue 264. Currently, this is nowhere close to being ready to merge, but I wanted some feedback. 

All of these points also have associated TODO items in the code.

- There are a number of classes that I've tightly coupled AnyKeyboardView to, and that is a clear sign that something needs to change with the organization of my code. I would love suggestions.
- I have no idea how to make the corrections work properly, or how to get the data I need for automatic capitalization and spacing (see AnyKeyboardView onTouch)
- I added a wordlist txt file, because I couldn't figure out how to get a list of words from the native dictionary
- I have no clue how to access the character associated with a key (I was getting weird null errors), so I used label instead. This is obviously a horrible hack
- It currently checks that you started your gesture near a key with a latin a-z or A-Z key to see if gesturing is enabled. Also a massive hack (see GestureTypingDetector isValidStartTouch)
- The gesture detector currently is very picky, but I want to get the issues above sorted out before tackling that. My plan was to implement something similar to the linked paper in the issue, but it looks like that will require a linear scan through all of the words in the dictionary (see the TODO item). If you can think of a way of optimizing this (perhaps some kind of tree? I'll see if the paper has a suggestion for this), that would be great, but for the first release I think a linear scan should be fine.

I am willing to work through all of these issues, but I think a second set of more experienced eyes would be great. I really appreciate you taking the time to review this!

### CODE REVIEW

**Comment by menny** [comment]
okay.. this is pretty awesome.
I've tested it on my device.

**Comment by menny** [comment]
If anyone wants to try it out: https://55-4063516-gh.circle-artifacts.com/0/tmp/circle-artifacts.fZEXnAe/apks/app-debug.apk

Don't forget to enable Gesture-Typing in settings (under Gestures, obviously)

**Comment by menny** [comment]
I'll give you write access to this repo. Please close this PR, and push your branch to this repo. We'll work on it together? Sounds good?

**Comment by menny** [comment]
I think that we'll need to move the logic into a new jni-dictionary.

**Comment by menny** [comment]
@jtjj222 how's your C++ skills?

**Comment by jtjj222** [comment]
I've worked with C++ before, but not much. I'm certainly happy to learn, as long as we can run some tests to make sure I don't create any nasty code execution bugs.

I am happy to push my branch to this repo, but first, I want your feedback on how to structure the code. I made a number of members public so that I could get this to work, and I know moving forward that this is a terrible idea.

Thanks for feedback, and I'm really looking forward to getting this to work!

**Pull request closed without merging**
