### PR TITLE
Missed updating graphics

### PR DESCRIPTION
**Pull request by wahballat**
Hi,

I apologize for missing this from my last commit. Please accept the updated graphics.

Thank you

### CODE REVIEW

**Comment by menny** [comment]
I think I these changes in the release repo: https://github.com/AnySoftKeyboard/AnySoftKeyboard/tree/release-branch-addons-v4.1-r2

**Comment by wahballat** [comment]
I will correct the locale to xna.

Do you want me to pull the release repo and commit my changes to it?  I just noticed that the Google Play Store entry uses the wrong graphics, and wasn't sure if this is how to fix it.

**Comment by menny** [comment]
Yes, please pull the release branch and make the fixes there

**Comment by wahballat** [comment]
The screenshots are correct in the branch but not that icon. But on the Google Play Store it shows the wrong screenshots https://play.google.com/store/apps/details?id=com.anysoftkeyboard.languagepack.oldnortharabian&hl=en_US&gl=US

**Comment by menny** [comment]
I think that's the icon will be updated once we roll out a new version

**Comment by menny** [comment]
Is that they only issue?

**Pull request closed without merging**
