### PR TITLE
Made reference to app store independent of Google

### PR DESCRIPTION
**Pull request by PanderMusubi**
Improved translations:
- where possible, refer to app store, or translation
- refer to Google Play, not Google Play Store

### CODE REVIEW

**Comment by menny** [comment]
You should only change the test in `src/main/res/values/strings.xml`.
Once this is merge, I'll update https://crowdin.com/project/anysoftkeyboard and it will be possible to update the translations.
Any other flow will cause overwriting the translations.

**Comment by PanderMusubi** [comment]
Can you pick the src/main/res/values/strings.xml from my pull requenst? It is in there. Please, refer the translaters to my translations so that they are done in a same way? As far as I can see, my proposals are good to use.

**Comment by PanderMusubi** [comment]
Will do that and report back here once that has been merged.

**Comment by menny** [comment]
@PanderMusubi you should rebase your branch to latest master

**Comment by PanderMusubi** [comment]
I completed Dutch translation today to 100%. Once that is available on GitHub, I will make a new fork and new pull request.

**Comment by menny** [comment]
got it.

**Comment by menny** [comment]
@PanderMusubi can you join https://gitter.im/AnySoftKeyboard/localization

**Comment by PanderMusubi** [comment]
Please reject this pull request. I will make a new one from a fresh fork.

**Comment by menny** [comment]
this was fixed in a different PR

**Pull request closed without merging**
