### PR TITLE
add english_qwerty_no_apstrophe layout

### PR DESCRIPTION
**Pull request by prg318**
Hello,

This pull request is to address https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1704

This PR adds a new keyboard layout named "qwerty_no_apostrophe" that is a copy of "qwerty_with_symbols", except the apostrophe key has been removed and replaced with centering for the "a" to "l" row of keys.

I originally had changed the symbols on this keyboard to be more common symbols for US users, but decided to hold back that part of the patch and keep the symbols exactly the same as "qwerty_with_symbols" for now, because I wanted to keep the PR isolated to a single issue.  I will likely make an additional pull request in the future that introduces or replaces the existing symbol layouts with more frequently used keys, but that is for another day.

### CODE REVIEW

**Comment by prg318** [comment]
Thank you!  I've added a commit that includes a unique id

**Comment by nicoursi** [comment]
> Thank you! I've added a commit that includes a unique id

Another reason why it's failing the tests is that there are two index=3 ;)
You should probably add it at the end of the list with index= 11 ;)

**Comment by nicoursi** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/63b2e88501fab6cff1332a098ce71ac1e5131033/ime/app/src/test/java/com/anysoftkeyboard/keyboards/KeyboardFactoryTest.java#L38

This should be 11 now I think, as you added one more :) Removing a single apostrophe from a keyboard can be this  complicated  ;)

**Comment by prg318** [comment]
It probably wouldn't be too bad if the failure messages from the tests were easy to find instead of being buried in tens of thousands of lines of gradle output

**Comment by nicoursi** [comment]
I completely agree with you and I have great news. There is a search box in the top right corner. Just type `failed` and you'll find the errors. I just discovered that recently 😉

**Comment by nicoursi** [comment]
You can also build it locally with `./gradlew testDebugUnitTest` If your computer is faster than mine

**Comment by prg318** [comment]
I might just keep my own fork of ASK as I don't have the time to update all of these tests.  Thanks for the tips

**Comment by prg318** [comment]
FYI when I search "failed" on the test details for "checks / app-tests-shards (1,2)", it says there are 0 results

**Comment by nicoursi** [comment]
Don't search with the browser search function. Use the search box

**Comment by prg318** [comment]
I am using the search box in the page

**Comment by prg318** [comment]
I just copied the contents of the test results into a text editor and used CTRL-F and found

 java.lang.AssertionError: expected:<10> but was:<11>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at com.anysoftkeyboard.keyboards.KeyboardAddOnTest.testGetEnabledDefaultFromAllKeyboards(KeyboardAddOnTest.java:54)


So it's saying it should be 10 now?

**Comment by nicoursi** [comment]
You can try having a look inside and see what's going on.

**Comment by prg318** [comment]
my local tests are failing from things seemingly completely unrelated to my change:
```
com.anysoftkeyboard.api.KeyCodesTest > testVerifyKeyCodesHasUniques FAILED
    java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final org.robolectric.internal.IShadow field org.robolectric.shadow.api.Shadow.SHADOW_IMPL to org.robolectric.internal.bytecode.ShadowImpl
        at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:223)
        at org.robolectric.internal.bytecode.Sandbox.configure(Sandbox.java:84)
        at org.robolectric.internal.SandboxTestRunner.configureSandbox(SandboxTestRunner.java:202)
        at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:220)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:96)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:830)

        Caused by:
        java.lang.RuntimeException: java.lang.IllegalAccessException: Can not set static final org.robolectric.internal.IShadow field org.robolectric.shadow.api.Shadow.SHADOW_IMPL to org.robolectric.internal.bytecode.ShadowImpl
            at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:208)
            at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:221)
            ... 44 more

            Caused by:
            java.lang.IllegalAccessException: Can not set static final org.robolectric.internal.IShadow field org.robolectric.shadow.api.Shadow.SHADOW_IMPL to org.robolectric.internal.bytecode.ShadowImpl
                at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:76)
                at java.base/jdk.internal.reflect.UnsafeFieldAccessorImpl.throwFinalFieldIllegalAccessException(UnsafeFieldAccessorImpl.java:80)
                at java.base/jdk.internal.reflect.UnsafeQualifiedStaticObjectFieldAccessorImpl.set(UnsafeQualifiedStaticObjectFieldAccessorImpl.java:77)
                at java.base/java.lang.reflect.Field.set(Field.java:780)
                at org.robolectric.util.ReflectionHelpers.setStaticField(ReflectionHelpers.java:206)
                ... 45 more

```

**Comment by nicoursi** [comment]
```
 com.anysoftkeyboard.ime.AnySoftKeyboardKeyboardSubtypeTest > testAvailableSubtypesReported FAILED
    java.lang.AssertionError: expected:<8> but was:<9>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at
```

things are getting out of hand. Maybe it's better to wait for the maintainers ;) was your code rebased? Last time something similar happened to me was because I merged instead of rebasing and corrupted the code

**Comment by prg318** [comment]
Indeed, this is getting quite out of hand.

I just rebased my repository against master

**Comment by prg318** [comment]
I also pushed a commit that reverted the subtypes test assertation, because my changes should not have affected the number of subtypes AFAIK

**Comment by nicoursi** [comment]
> sed my

normally what works is `git pull --rebase upstream master` and then force push (you are the only one updating the code, so it's ok) `git push -f origin HEAD`

But if it is already corrupted you don't fix it that way any more, I guess. I am new to git, so this is what I know and works for me.

**Comment by prg318** [comment]
I have "AnySoftKeyboard/AnySoftKeyboard.git" as a  "upstream" remote in my git configuration.. I then did "git fetch upstream" and "git rebase upstream/master"

Not sure how my repository could be "corrupted"

**Comment by nicoursi** [comment]
as the change you made is very minimal, you can rebase master, create a new branch, apply the new layout into this new branch, rename  `add-english-qwerty-no-apostrophe` into `add-english-qwerty-no-apostrophe_old` and rename again the new branch into `add-english-qwerty-no-apostrophe`. Now force push again `git push -f origin HEAD`

**Comment by nicoursi** [comment]
> I have "AnySoftKeyboard/AnySoftKeyboard.git" as a "upstream" remote in my git configuration.. I then did "git fetch upstream" and "git rebase upstream/master"
> 
> Not sure how my repository could be "corrupted"

Look at the files changes, you now have 13 files changed, you did indeed corrupt the code ;)

**Pull request closed without merging**
