### PR TITLE
Improved Piedmontese dictionary and frequencies with data from piemunteis.it

### PR DESCRIPTION
**Pull request by glemco**
I can see that the [Piedmontese language pack] app was not published yet, what should I do to have it published (by AnySoftKeyboard would be fine) on PlayStore and F-droid?

### CODE REVIEW

**Comment by lubenard** [comment]
Hello ! This app has been published on Google Play store [here](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard)

and on F-droid [here](https://f-droid.org/packages/com.menny.android.anysoftkeyboard/)

**Comment by glemco** [comment]
> Hello ! This app has been published on Google Play store [here](https://play.google.com/store/apps/details?id=com.menny.android.anysoftkeyboard)
> 
> and on F-droid [here](https://f-droid.org/packages/com.menny.android.anysoftkeyboard/)

Hello! I realize now that isn't exactly clear.. I'm aware that the keyboard itself has been published, but the Piedmontese dictionary hasn't yet (this is just the second commit for it).
Anyway, I found again that weird glitch on F-droid, where the main app's name is one package's name (here AnySoftKeyboard has the name of the Piedmontese pack itself..). Maybe something has been done to attempt to publish it..

**Comment by lubenard** [comment]
Yes, seems like a bug, you can see it under #2161, #2334 and #2211

**Comment by glemco** [comment]
> Yes, seems like a bug, you can see it under #2161, #2334 and #2211

Thanks for the answer! Sounds even a rather old bug..

**Pull request merged**
